services:
  - type: web
    name: alipay-h5-login
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALIPAY_APP_ID
        sync: false
      - key: ALIPAY_APP_PRIVATE_KEY
        sync: false
      - key: ALIPAY_PUBLIC_KEY
        sync: false
      - key: ALIPAY_GATEWAY_URL
        value: https://openapi.alipaydev.com/gateway.do
      - key: ALIPAY_OAUTH_GATEWAY_URL
        value: https://openauth.alipaydev.com/oauth2/publicAppAuthorize.htm
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO